from pathlib import Path
from .custom_classes import LogFile
import os

def write_hyprland_config(user_home: Path, log: LogFile):
    """Writes the default SENDUNE Hyprland configuration."""
    config_dir = user_home / ".config" / "hypr"
    config_file = config_dir / "hyprland.conf"
    
    try:
        config_dir.mkdir(parents=True, exist_ok=True)
        
        # --- 1. Hyprpaper Config (Wallpaper) ---
        wallpaper_path = "/usr/share/backgrounds/sendune/sendune_wallpaper.png"
        hyprpaper_conf = f"""
preload = {wallpaper_path}
wallpaper = ,{wallpaper_path}
splash = false
"""
        with (config_dir / "hyprpaper.conf").open("w") as f:
            f.write(hyprpaper_conf)

        # --- 2. Hyprland Config ---
        # Simple base config for ML4W / Sendune style
        conf_content = """
# #######################################################################################
# AUTOGENERATED HYPR CONFIG.
# PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
# OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
# #######################################################################################

#
# SENDUNE Hyprland Configuration
# Based on ML4W Dotfiles
#

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = waybar & hyprpaper & mako

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Set programs that you use
$terminal = foot
$fileManager = thunar
$menu = wofi --show drun

# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 to disable the anime mascot wallpapers
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -0.5
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating, 
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
"""
        with config_file.open('w') as f:
            f.write(conf_content)
            
        # Ensure ownership is correct if running as root (not needed in Mock/Windows usually due to perms)
        # But good practice for Linux
        if os.geteuid() == 0:
            import pwd
            try:
                # We need to resolve the user ID from the path or pass it in.
                # Assuming user_home is like /home/username
                username = user_home.name
                pw = pwd.getpwnam(username)
                os.chown(config_file, pw.pw_uid, pw.pw_gid)
                os.chown(config_dir, pw.pw_uid, pw.pw_gid)
            except Exception as e:
                log.warn(f"Could not chown config file: {e}")

        log.info(f"Written SENDUNE Hyprland config to {config_file}")
        
    except Exception as e:
        log.error(f"Failed to write Hyprland config: {e}")

def write_bashrc(user_home: Path, log: LogFile):
    """Writes a custom .bashrc that restricts pacman usage."""
    bashrc_file = user_home / ".bashrc"
    
    try:
        # Read existing .bashrc if it exists
        existing_content = ""
        if bashrc_file.exists():
            with bashrc_file.open("r") as f:
                existing_content = f.read()
        
        # Add SENDUNE customizations
        sendune_content = """
# SENDUNE Customizations
# Restrict direct pacman usage - use 'flip' instead
alias pacman='echo "Direct pacman usage is disabled. Use flip instead. Run flip help for commands."'
alias sudo='sudo '  # Allow sudo to work with aliases

# Add flip to PATH if not already
export PATH="$PATH:/usr/local/bin"

# SENDUNE welcome message
echo "Welcome to SENDUNE Linux! Use 'flip' for package management."
"""
        
        with bashrc_file.open("w") as f:
            f.write(existing_content + "\n" + sendune_content)
        
        # Set ownership
        if os.geteuid() == 0:
            import pwd
            try:
                username = user_home.name
                pw = pwd.getpwnam(username)
                os.chown(bashrc_file, pw.pw_uid, pw.pw_gid)
            except Exception as e:
                log.warn(f"Could not chown .bashrc: {e}")
        
        log.info(f"Updated .bashrc to restrict pacman at {bashrc_file}")
        
    except Exception as e:
        log.error(f"Failed to write .bashrc: {e}")
